// src/components/CreateWardModal.jsx
import { useState } from "react";
import { X, Plus, Building } from "lucide-react";
import { wardsApi } from "../apiClient";

const CreateWardModal = ({ isOpen, onClose, onWardCreated }) => {
  const [formData, setFormData] = useState({
    name: ""
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!formData.name.trim()) {
      setError("Ward name is required");
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const { data: createdWard } = await wardsApi.create({
        name: formData.name.trim()
        // id is generated by backend, admissions is initially empty
      });
      
      // Reset form and close modal
      setFormData({ name: "" });
      onWardCreated(createdWard); // Callback to refresh wards list
      onClose();
      
    } catch (error) {
      console.error("Error creating ward:", error);
      if (error.response?.status === 403) {
        setError("Access forbidden: You don't have permission to create wards.");
      } else {
        setError(error.response?.data?.message || "Failed to create ward. Please try again.");
      }
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
    // Clear error when user starts typing
    if (error) setError(null);
  };

  const handleClose = () => {
    setFormData({ name: "" });
    setError(null);
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50 transition-opacity duration-300">
      <div className="bg-white rounded-lg border border-gray-200 w-full max-w-md shadow-2xl">
        {/* Modal Header */}
        <div className="flex items-center justify-between p-4 border-b border-gray-200">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-blue-100 rounded-full">
              <Building className="w-5 h-5 text-blue-600" />
            </div>
            <div>
              <h2 className="font-bold text-lg text-gray-800">Create New Ward</h2>
              <p className="text-sm text-gray-600">Add a new ward to the hospital</p>
            </div>
          </div>
          <button
            onClick={handleClose}
            className="p-1 hover:bg-gray-100 rounded-full transition-colors"
            disabled={loading}
          >
            <X className="w-5 h-5 text-gray-500" />
          </button>
        </div>

        {/* Modal Content */}
        <form onSubmit={handleSubmit} className="p-4">
          {error && (
            <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg">
              <p className="text-sm text-red-700 font-medium">{error}</p>
            </div>
          )}

          <div className="space-y-4">
            <div>
              <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-1">
                Ward Name *
              </label>
              <input
                type="text"
                id="name"
                name="name"
                value={formData.name}
                onChange={handleChange}
                placeholder="e.g., Emergency Ward, ICU, Pediatrics..."
                className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm text-gray-800 focus:ring-blue-500 focus:border-blue-500 transition-colors"
                disabled={loading}
                autoFocus
              />
              <p className="mt-1 text-xs text-gray-500">
                Enter a descriptive name for the new ward
              </p>
            </div>

            {/* Optional: Add capacity field if your backend supports it */}
            {/* <div>
              <label htmlFor="capacity" className="block text-sm font-medium text-gray-700 mb-1">
                Capacity (Optional)
              </label>
              <input
                type="number"
                id="capacity"
                name="capacity"
                value={formData.capacity || ''}
                onChange={handleChange}
                placeholder="e.g., 20"
                min="1"
                className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm text-gray-800 focus:ring-blue-500 focus:border-blue-500 transition-colors"
                disabled={loading}
              />
            </div> */}
          </div>

          {/* Modal Actions */}
          <div className="flex gap-2 pt-4 mt-4 border-t border-gray-200">
            <button
              type="button"
              onClick={handleClose}
              className="flex-1 px-4 py-2 text-sm border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors font-medium disabled:opacity-50"
              disabled={loading}
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading || !formData.name.trim()}
              className="flex-1 px-4 py-2 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium shadow-md flex items-center justify-center gap-1 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                  Creating...
                </>
              ) : (
                <>
                  <Plus className="w-4 h-4" />
                  Create Ward
                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default CreateWardModal;